// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const MinimalLazyImport = createFileRoute('/minimal')()
const MaximalLazyImport = createFileRoute('/maximal')()

// Create/Update Routes

const MinimalLazyRoute = MinimalLazyImport.update({
  path: '/minimal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/minimal.lazy').then((d) => d.Route))

const MaximalLazyRoute = MaximalLazyImport.update({
  path: '/maximal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/maximal.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/maximal': {
      preLoaderRoute: typeof MaximalLazyImport
      parentRoute: typeof rootRoute
    }
    '/minimal': {
      preLoaderRoute: typeof MinimalLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MaximalLazyRoute,
  MinimalLazyRoute,
])
